$(document).ready(function(){
    $('.banner-slider').owlCarousel({
        loop:true,
        margin:20,
        nav:false,
        autoplay:true,
        responsive:{
            0:{
                items:1,
                nav:false,
            },
            600:{
                items:1,
                nav:false,
                dots:true,
            },
            1000:{
                items:1
            }
        }
    })
    
    $('.blog-slider').owlCarousel({
        loop:true,
        margin:20,
        nav:true,
        dots:false,
        autoplay:true,
        responsive:{
            0:{
                items:1,
                nav:false,
                dots:true,
            },
            600:{
                items:2,
                nav:false,
                dots:true,
            },
            1000:{
                items:3
            }
        }
        })

        $('.client-slider').owlCarousel({
            loop:true,
            margin:20,
            nav:true,
            dots:false,
            autoplay:true,
            responsive:{
                0:{
                    items:1,
                    nav:false,
                    dots:true,
                },
                600:{
                    items:1,
                    nav:false,
                    dots:true,
                },
                1000:{
                    items:1
                }
            }
        })
});